### ISSUE TITLE
Removing Categories and Tags when switching post types to Likes and Notes?

### ISSUE THREAD

**Issue by nsmsn** [janboddez/indieblocks#124]
I'm working on a content migration from micro.blog, and used a Post Type switcher plugin to convert some of my older posts into Notes and Likes. If they have any category or tag associated with them (even "Uncategorized") these are carried over to the new post type. 

Is there a way I can remove these from my Notes and Likes, since the default behavior only shows longer posts with those categories and tags?

**Comment by janboddez** [comment]
I think this is WordPress core's doing. (I mean, I'm assuming you have the "Enable categories and tags" option disabled for the note and like post types? Because that _would_ enable "regular" post tags and categories _also_ for these custom post types. I don't think it automatically adds the default category, though. [One could use an action callback for that.])

For a generic (for all WordPress installations) approach, using WP-CLI, I'd look at https://developer.wordpress.org/cli/commands/post/term/remove/.

Something like:
```
for x in $(wp post list --post_type=indieblocks_like,indieblocks_note --format=ids) ; do wp post term remove $x post_tag --all ; wp post term remove $x category --all ; wp post term remove $x category uncategorized ; done
```
That should delete all categories and tags for only our two post types.

(The problem is `wp post term remove <id> category --all` actually re-adds the default category. Luckily, running `wp post term remove <id> category uncategorized` after it works, too.)

**Comment by janboddez** [comment]
> [T]he default behavior only shows longer posts with those categories and tags?

This can be adjusted in WordPress' permalinks settings. I think the default might be for note tag archives to be shown at `/notes/tag/something`. By changing the tag and category permalinks, however, it is possible to have _all_ post types included at "just" `/tag/something`. That's what I do. E.g., at https://jan.boddez.net/tag/share-on-mastodon, you'll see both posts ("articles") _and_ notes.

What worked for me was to simply "hardcode" the tag and category prefixes:

![image](https://github.com/janboddez/indieblocks/assets/8428432/804a0ae4-dc69-4ddf-99d9-8d8e94022a68)

**Comment by janboddez** [comment]
(In general, permalinks and custom post types are super powerful, so it's all about finding a middle ground between not screwing up existing sites yet letting users set things up according to their needs, which sometimes may even involve custom code. Like, you _could_ totally override notes' permalinks beyond the UI options, even turn them into `/microblog/<yyyy>/<mm>/<something>.`)

**Comment by nsmsn** [comment]
Thanks, this is great info. On further reflection, I decided I'm better off using categories and tags for everything.  Thanks for making these options flexible in the IndieBlocks settings.

**Comment by janboddez** [comment]
(Purely FYI) It's not too hard to define custom taxonomies either, if you wanted to keep them separate from post/article tags and categories. All up to you.

Some have even argued that notes/likes _should_ in fact be "just" posts, and that custom taxonomies (like those from the _Post Kinds_ plugin) are a more appropriate way to "separate" them [yet keep them in your site's overall feed, etc.]. There really is no right or wrong here. I chose post _types_ because I _want_ to have WP's admin interface list them separately. I also believe post types are a little easier to deal with when it comes to block templates, etc.

(Sorry for the technicalities. I've probably thought about these things way more than I should've. Makes it real hard to write proper, easily digestible end-user documentation too.)

**Comment by janboddez** [comment]
(In general) Like any other plugin, this here one is nothing but a (whole) bunch of action/filter callbacks. It's "relatively" easy¹ to have a custom callback with a higher prio override them (like if you wanted to tweak the custom post type definitions), or unhook them and replace them with your own.

1. For a somewhat seasoned PHP/WP dev
