### ISSUE TITLE
Reply Block

### ISSUE THREAD

**Issue by nsmsn** [janboddez/indieblocks#128]
It looks like the reply block is not formatted with the recommended `class="u-in-reply-to"` micro formats markup. https://indieweb.org/in-reply-to

I tried out the https://webmention.rocks test suite and had to manually mark up a link with this class for it to process as a proper webmention reply.

Caveat: I'm new to IndieWeb, Webmention, and Microformats, so I could be doing it wrong?

Let me know if there is a reason if this property can't be supported in a future release of the plugin.

**Comment by janboddez** [comment]
Oh, that's interesting, thanks!

Unfortunately, https://webmention.rocks is down for me right now.

I often test against Aaron Parecki's X-Ray parser (which is built on top of the php-mf2 library), and it seems replies get recognized as such:
https://xray.p3k.io/parse?url=https%3A%2F%2Fjan.boddez.net%2Fnotes%2F252927130f&pretty=true

That post's reply block looks like this (I mean, you could see that, but it's easier to visualize it here):
```
<div class="wp-block-indieblocks-reply">
  <div class="u-in-reply-to h-cite">
    <p><i>In reply to <a class="u-url" href="https://social.johanbove.info/2023/07/31/yesterday-i-burned-a-bunch-of-mp3s">https://social.johanbove.info/2023/07/31/yesterday-i-burned-a-bunch-of-mp3s</a> by <span class="p-author">Johan Bové</span>.</i></p>
  </div>
  <div class="e-content">
    <p>I was just thinking about this, or rather, about what I used to listen to in the car, and how. It’s been mostly classical radio these last few years, but my previous car had an SD card slot, and I’d always have about a dozen albums in there. (My current car has a USB slot, but I just … stopped using it a couple years ago?) I don’t care for anything that involves a phone.</p>
    <p><em>Stuff I remember listening to (other than, say, late-’90s skate punk) quite a bit: Robyn, Katy Perry, Hatebreed, Bright Eyes. </em></p>
  </div>
</div>
```

The wiki also mentions, "The microformats2 `u-in-reply-to h-cite` class names can also be used to embed a [reply-context](https://indieweb.org/reply-context) with more details beyond the URL," which is what I was going for here.

See also the [example markup on the reply context page](https://indieweb.org/reply-context#Markup):
```
<div class="h-entry">
 <div class="u-in-reply-to h-cite">
  <p class="p-author h-card">Hannah</p>
  <p class="p-content">I am eating a donut</p>
  <a class="u-url" href="permalink"><time class="dt-published">YYYY-MM-DD</time></a>
 </div>
 
 <p class="p-author h-card">Sarah</p>
 <p class="e-content">Is it from Blue Star?</p>
</div>
```

But, once the test suite is back up, I'll give it another look.

**Comment by janboddez** [comment]
> had to manually mark up a link with this class

Just for clarity: the class isn't on the link, it's on the `.h-cite` element. Or should be. The older Context block would have it on the link, but that block does not support "reply (or any other) context."

**Comment by nsmsn** [comment]
Oh, I see it now... Thanks for clarifying. Yes, unfortunately, the Webmention.rocks is down for me now, too.

**Comment by janboddez** [comment]
I had a look and was a bit confused because there doesn't seem to be a specific _microformats_ test, but then I clicked through and saw what you mean.

I had a look at the test suite's repo and stumbled across https://github.com/aaronpk/webmention.rocks/issues/38; now, I didn't dig too deep, but to me this looks like an issue with the test suite.

**Sidenote:**

Can recommend http://pin13.net/mf2/ to verify microformats. It should show an `in-reply-to` property (for replies, at least). It is this property that [X-Ray](https://xray.p3k.io) uses to determine the post type. (I use both tools regularly.)

Note that "post type discovery" depends on the presence of **all** such properties. ([X-Ray's](https://github.com/aaronpk/XRay/blob/main/lib/XRay/PostType.php) is but one implementation. Like, you could have a Like block and a Reply block in one and the same post, and X-Ray would label it a "like." Whereas another app might consider it a reply.)

This ambiguity is ... kind of a feature (I didn't create separate post types for bookmarks, reposts, etc. for a reason). A post's "type" (in the IndieWeb sense of the word) is purely determined by its contents _only_. (The only reason the "like" post type exists, is because quite a few people, myself included, don't want likes included with the rest of their "notes." Yet other people use likes as a type of bookmark, _with_ body content and so on; in that case, it _does_ make sense to not separate them. [Luckily, it is possible to use the Like block also inside a "note."]) :-)

**Comment by nsmsn** [comment]
Thanks for checking back in and including this information. I'll check out the links you shared.

I think my sending and receiving Webmentions is working as expected on my website right now.

Thanks again!
