### ISSUE TITLE
Fatal error?

### ISSUE THREAD

**Issue by nsmsn** [janboddez/indieblocks#160]
I was in a chat with my hosting company (getflywheel.com) about another issue and they detected an error on my site:

[pool site-nicksimson.com] child 240183 said into stderr: "NOTICE: PHP message: PHP Fatal error: Uncaught Error: Call to a member function get_error_message() on array in /www/wp-content/plugins/indieblocks/includes/class-webmention-sender.php:260"

Any idea what could be causing this? I'm also running the Webmention plugin.

**Comment by janboddez** [comment]
Ha, thanks for reporting.

Must be due to the if condition:
https://github.com/janboddez/indieblocks/blob/8b8a36a26238c2922043511ebec6e49fe200574c/includes/class-webmention-sender.php#L258-L260

Since `$response` is (apparently) not a `WP_Error` object, must be the remote endpoint returned a server error (`500` or up).

I'll have to fix that.

**Comment by janboddez** [comment]
So, the "good" thing is, your site didn't really break, but that mention never got sent due (or, well, it did, but the remote server returned some kind of error), and the retry never got scheduled ... because of the fatal error.

> I'm also running the Webmention plugin.

You may want to try disabling IndieBlocks' Webmention option, then. Or maybe you already did? I mean, if it _is_ indeed disabled, this function should not ever get called ...

**Comment by janboddez** [comment]
So, bf1a2d2 should at least get rid of the fatal error.

**Comment by nsmsn** [comment]
What's the best way to test this update? I'm using the plugin in the wordpress.org directory. I suppose I can set up a staging site and upload this new version of the plugin. I just don't want to wipe out all my /notes and /likes by removing the plugin from my live site.

**Comment by janboddez** [comment]
> I just don't want to wipe out all my /notes and /likes by removing the plugin from my live site.

Won't happen. ;-) Removing the plugin will temporarily disable the URLs but not wipe the data. (But I hope your host provides backups nonetheless!)

If you want to, you _should be able to_ replace only `/includes/class-webmention-sender.php` with https://raw.githubusercontent.com/janboddez/indieblocks/93cf03c31c9a12ece326dc6c626dd0de5cd3c6c1/includes/class-webmention-sender.php.

Or wait till I release this. :-)

Again, if you don't have _IndieBlocks'_ Webmention option enabled, this error shouldn't occur, ever. So I'm not sure what exactly is going on in that regard.

**Comment by nsmsn** [comment]
I updated the plugin file and the error message is no longer showing up. Thank you, Jan!

I think I had both the Webmention plugin enabled plus IndieBlocks webmentions running at the same time at one point. I will be sure to update the plugin to the next update.
