### ISSUE TITLE
Latest Webmention update "kills" IndieBlocks Facepile

### ISSUE THREAD

**Issue by cybeardjm** [janboddez/indieblocks#182]
The 5.3.x Webmention update fixed a problem with the standard WP Facepile, but it seems it has "killed" the optional (and experimental) IndieBlocks Facepile.
I added the IndieBlocks facepile to my template a long time ago, due to the way the "Bridgy" comments were managed in new themes like Twenty-Twenty-Three.
The latest Webmention update corrects the problem, but then the IndieBlocks facepile disappeared and I had to deactivate the option to get the likes and boosts reapper on my posts.

**Comment by janboddez** [comment]
I think it now _always_ removes likes etc. from the comment query and that that is why they also disappear from the Facepile block.

IndieBlocks has always done the same but makes sure to temporarily _remove_ this filter for the Facepile block (because otherwise it wouldn't work, obviously).

I'll now also have to remove the Webmention filter, or add its comment types back in _explicitly_. Will look into it, shouldn't be too hard!

**Comment by janboddez** [comment]
Meanwhile you may be able to uncheck the Webmention plugin's "separate facepile" option or whatever it's called. If you use the core WP Comments block, at least, there's no need for that to be checked, since IndieBlocks handles this already.

Edit: Oh, I think you're saying you did that already! My bad!

**Comment by janboddez** [comment]
Should be fixed in v0.13.0, which I'm planing to release very soon.

**Comment by janboddez** [comment]
Works for me. The one thing I aim to improve and I think may have worked before is I wanna keep displaying Webmention avatar URLs even if the Webmention plugin is disabled, i.e., still have IndieBlocks recognize them.

**Comment by cybeardjm** [comment]
Works for me too.
What's funny is although the option is disabled in the backoffice, as I added the block manually to the theme, the block's there, as are the regular Webmention ones...
As the presentation is different, I can live with that...
Thx

**Comment by janboddez** [comment]
> What's funny is although the option is disabled in the backoffice, as I added the block manually to the theme, the block's there, as are the regular Webmention ones...

Do you have a link? To a page with a Facepile block (and other comments)?

If you've added the block to your theme, you don't need to auto-add it anymore.

Do you mean the Webmention plugin now also displays its own facepile? Like it always did for non-block themes? If possible, I'd like to keep the Facepile block compatible.

**Comment by cybeardjm** [comment]
Yep, I now have both, although I didn't activate it in the BO...
https://www.didiermary.fr/feeding-cat-instincts/

**Comment by janboddez** [comment]
Oh, and you have Webmention's (not IndieBlocks') option to separately display a facepile **disabled**? That is indeed kind of strange.

Although I guess you could always remove the Facepile block.

I only created the Facepile block to give block theme users _more freedom_, in where they wanted the block to appear.

I only later---IndieBlocks comes with its own implementation of the Webmention protocol, it does not need the Webmention plugin---made it "compatible" also with the Webmention plugin, _because_ that plugin _was_ kind of broken in combination with block themes.

**Comment by cybeardjm** [comment]
For now, I disabled both options (“Facepile” bookmarks, likes, and reposts & Auto-insert Facepile block) in Indieblocks' Webmention (disabled too, BTW) => have all visible
If I disable "Separate Webmention Types from Comments." for the Webmention plugin, IndieBlocks' facepile is still fine, and the webmentions become regular "Bridgy response" comments.

**Comment by janboddez** [comment]
I see!

Can you try enabling IndieBlocks' “Facepile” bookmarks, likes, and reposts, and disable Webmention's "Separate Webmention Types from Comments"? That should fix the "Bridgy response."

**Comment by janboddez** [comment]
"Separate Webmention Types from Comments" will show Webmention's facepile (and [correctly] get rid of the Bridgy response thing).

IndieBlocks' Facepile block is (obviously) what's used for IndieBlocks' Facepile, but you still need to enable the ‘“Facepile” bookmarks, likes, and reposts’ option to get rid of the "Bridgy response." I'm still looking into that happening automatically, but alas.¹

Then you don't need to enable "Separate Webmention Type" and you won't get the "double" facepile ...

1. The closest I've gotten is auto-insert a Facepile block, although it still isn't 100% there. That's why for now it's a separate option. In the future I might merge both.

**Comment by cybeardjm** [comment]
Indeed, this works "as intended"...
Now you know, there's something "floating" around where both blocks can appear...

**Comment by janboddez** [comment]
Yeah, sorry for the confusion!

It's really two plugins trying to do the same thing or something rather similar ...

I guess the ideal scenario is ... use only one of them. :-)

Hopefully in the future I'll have only one "Facepile" setting that will both separate out likes, etc. from regular comments __and__ insert a Facepile block (but then you'll have to delete any manually inserted Facepile blocks ... or you'll also see two such blocks). The good thing is, you can go in and edit the template, even move the "automatically inserted" block around or anything, and WordPress will actually remember those changes (and not, e.g., insert more copies of it).

Either way, glad it works!
