### ISSUE TITLE
Plugin update obscures Gravatar, UI in post-new.php

### ISSUE THREAD

**Issue by nsmsn** [janboddez/indieblocks#192]
![Screenshot 2024-07-15 at 10 47 46 AM](https://github.com/user-attachments/assets/9901a360-a69f-43c7-a6b6-a072be387061)

Not exactly sure if there is a plugin conflict here, but my Gravatar is replaced by a default pixel image and a large version of this image blocks out the Post/Bock UI in /wp-admin/post-new.php. I included a screenshot (above)

**Comment by nsmsn** [comment]
I reverted to version 0.12.0 for now...

**Comment by janboddez** [comment]
Oh, never seen this … If you're ever able to [disable all plugins and turn them back on one by one], that would probably help a lot.

**Comment by nsmsn** [comment]
I'll give this a shot in staging, with the updated Indieblocks plugin activated. I noticed an "avatar proxy option" in the v 0.13.0 release notes...

**Comment by janboddez** [comment]
Yeah, also changed something in how it retrieves (webmention) avatars; afraid it may have broken something else. I'll give it another look later tonight.

**Comment by nsmsn** [comment]
I found out exactly which plugin was creating the conflict. It's one called WP Toolbelt, and they have this module called "Avatars (Experimental)" which is a "privacy-focused replacement for Gravatar". Here's the documentation for the module: https://github.com/BinaryMoon/wp-toolbelt/wiki/Avatars

I do have a Gravatar profile, but I unchecked this module and the updated v 0.13.0 of IndieBlocks works on my staging site. 

I'm supposing the new IndieBlocks update was conflicting with that experimental module in WP Toolbelt.

**Comment by nsmsn** [comment]
I went ahead and made my staging changes on the live site. Thanks for the quick responses, Jan.

**Comment by janboddez** [comment]
> Here's the documentation for the module: https://github.com/BinaryMoon/wp-toolbelt/wiki/Avatars

Thanks, going to check that out!

IndieBlocks should "replace" only comment avatars, and it should do so only when there's either a Webmention avatar, or an "IndieBlocks' Webmention" avatar, or maybe an ActivityPub avatar. If not, it "should" just let WordPress (or another plugin) do its thing. (Except it doesn't, not always, because of the proxy thing. But again, that _should_ affect only comments.)

Anyway, still afraid I may have "messed up" someplace, so I want to have a look regardless.

Avatars are weird; WordPress gets them from Gravatar based on email addresses, but plugins can override the output in all sorts of ways, based on custom fields and whatnot.
