### ISSUE TITLE
How to Use IndieBlocks

### ISSUE THREAD

**Issue by tmichellemoore** [janboddez/indieblocks#47]
Hello @janboddez,
Can you tell me if there are any other required plugins for the IndieBlocks plugin?
And for Mastodon, then can you tell me how to use it and by that I mean, do you just pot a Like with the url of the Mastodon post, for example, and then publish the post? Or do you have to publish the post with some type of sharing?

I have all of the IndieWeb plugins installed except the ones that require the classic editor. In a reply to me on Mastodon a while back it seems like you mentioned that I might need to make an adjustment to something that related to Webmentions.

The reason I am asking is because I did test out the Likes today for a Mastodon post and I can't get it to work.

Thank you for your help!
Michelle

**Comment by janboddez** [comment]
Hi, there are no prerequisites for running IndieBlocks.

Except for Micropub/IndieAuth, which I use for posting from my phone, I don't use any of the other "IndieWeb" plugins.

Mastodon doesn't accept webmentions. So while you could use a _syndication_ plugin to share a "like" post (or any other post, for that matter) to Mastodon (or elsewhere), it would not result in an _actual_ like on Mastodon. 

Maybe Bridgy (Fed) has an option for that, I can't say.

What I do on my blog is thread certain replies, also on Mastodon (e.g., when I reply to a note on my blog and that note has been syndicated to Mastodon, and I choose to also syndicate the reply, it will be correctly "threaded" on Mastodon, too). But that has nothing to do with IndieBlocks per se.

IndieBlocks "only" provides a couple post types, adds microformats to _modern_ WP themes---you might have to tweak, in the Site Editor, and validate your templates, though---and sends out (to sites that support them) and receives webmentions. And provides the "Context" block, in order to not have to worry too much about microformatting replies and likes.

**Comment by tmichellemoore** [comment]
Thank you @janboddez! I get it now! Since you mentioned this > What app do you use for this -  "Except for Micropub/IndieAuth, which I use for posting from my phone"?

**Comment by janboddez** [comment]
Just seeing that last question now ... Sorry!

I use [Indigenous for Android](https://play.google.com/store/apps/details?id=com.indieweb.indigenous). (It was supposed to be eventually renamed to IndiePass, by the way. Seems that has yet to happen.)

**Comment by tmichellemoore** [comment]
Thank you. You can close this ticket.
