### ISSUE TITLE
Block for Likes Archive

### ISSUE THREAD

**Issue by jasontucker** [janboddez/indieblocks#57]
I'm proposing a block be built to be used for the Likes archive on a site where when the title is clicked the user is linked to the website liked. 

I've built my site using full site editor and have created a template for the like CPT When displaying the likes on the page there is no clean way to allow for the display of the link and make it clickable since the like doesn't have a title.

I have random slugs, autogenerate titles, hide titles all enabled.

With this proposed block you should be able to replace to post title with the like block allowing for it to be used to link to the correct liked site with the url or title if you are collecting or capturing it be displayed for the link.
![CleanShot 2023-02-21 at 13 50 45](https://user-images.githubusercontent.com/108426/220466763-5f6b2e91-b0ed-47a0-bfc9-baea5dbd847d.png)

**Comment by janboddez** [comment]
Kinda like a oEmbed thingy or “preview card”?

Way I have set up my likes archive is I create a custom post archive and then inside the Query Loop thingy I replace the Excerpt block with the full content (or I add a Post Content block if there isn’t one by default, it depends on the theme).

Bunch of themes show only titles and perhaps a date, so you have to adapt those anyway, also to have meaningful “h-feed” microformats (although those aren’t super important for webmentions as those will most often target individual posts).

**Comment by janboddez** [comment]
I’m in fact working on a bunch of blocks (that you would use inside post content, but still) that are able to display “linked page” titles and such. So maybe that would work as well.

I mean, _if_ your post content _is_ essentially one such “Like” block ...

**Comment by jasontucker** [comment]
I used Quill https://quill.p3k.io/ to create a "favorite" https://quill.p3k.io/favorite that posted to the like CPT and I wanted to display them as posts on my likes archive page. I'm thinking a block that uses the post template Post Title that instead of linking to the slug could link to the like url would take care of that. Is that what you were envisioning for the Link CPT and its archive page?
![CleanShot 2023-02-21 at 14 06 17](https://user-images.githubusercontent.com/108426/220469443-52f7326d-5f7c-48c0-82cf-b3392f5cf963.png)

**Comment by jasontucker** [comment]
you can see my likes archive here https://jasontucker.blog/likes and you can see that it doesn't have a title for the posts most likely because they are being supressed here from this option:

Hide Titles | Hide note and like titles(Experimental) Attempts to hide note and like titles, if you have enabled microformats and your theme supports the Full-Site Editor.

![CleanShot 2023-02-21 at 14 09 15](https://user-images.githubusercontent.com/108426/220469881-43c42584-9159-4250-bc7b-a0a30f3e80af.png)

**Comment by jasontucker** [comment]
Ok the content block helped with that! I think having a block you can customize for that title/url to be adjustable a bit with block options would be a really nice way to manage that.

**Comment by jasontucker** [comment]
Also.. Quill is all sorts of awesome, I found that linked on your site and wow is that thing so simple yet so easy to manage posting content on your site.

**Comment by janboddez** [comment]
Gotcha on the like title thing. I know https://adactio.com does something similar for their bookmarks.

Might be possible overriding the core Post Title block for likes (and/or bookmarks) only.

I myself don't use Quill but I do use an Android Micropub client that much does the same thing. Makes it really easy to post replies, likes, and bookmarks from my phone. (The official WordPress app doesn't do custom post types ...)

**Comment by janboddez** [comment]
Was thinking of stuffing this behind yet another option instead of introducing a whole new block.

The idea being that users can (if needed) override like and bookmark titles and even have them autogenerated, not based on the post content but on the linked (i.e., liked or bookmarked or maybe even reposted) page instead. So use the post title field rather than a block.

And then that same setting would also lead to "permalinks" being filtered/overridden so that they point at the external page instead of the local "like" or "note."

Except maybe we'd like to not filter the "date permalink" and only affect the "title permalink." ~~Which I don't think is possible. (Well, if so, users/admins can just turn it off again, I guess.)~~ May be possible by modifying the post title block (which we do anyway) rather than use a "generic" permalink filter.

**Comment by janboddez** [comment]
OK, so I'm going to introduce a new "Like" block, which will be able to automatically fetch the liked page's title. Because some pages can and will return weird titles, you'll be able to edit/override these.

There will also be an option to have likes' (i.e., instances of the like CPT) titles = the title of the liked page. (And something similar for bookmarks.) This will "suffer" from the same issue. If you use, e.g., Quill to publish such a like and do not provide a title, IndieBlocks will fetch it for you. If you provide one, that will be used instead. But if you use the Like block, i.e., in WP-Admin, IndieBlocks will use _whatever title is in there_ (if any). So the Like block will, in the end, let you override like titles.

Sounds more confusing than it is (hopefully). There's probably some edge cases I haven't considered, too, but ...

**Comment by janboddez** [comment]
This CPT title option will _also_ have a like's title link to the liked, i.e., external page ... (At least when you use the theme microformats ...)

**Comment by jasontucker** [comment]
Downlaoded the latest version and favorited a page using the Quill bookmarklet and having the title makes it much nicer non my Likes page, thank you.  https://jasontucker.blog/likes

**Comment by janboddez** [comment]
![image](https://user-images.githubusercontent.com/8428432/228188114-f52e5924-4b7b-4e82-a8ca-a4b9fb2259ed.png)

If you were to, later on, also enable the second option here, then the post title will be the "liked page's title" and you could again use that in your archive template (regular notes and replies would still get a title like, "In reply to ..." or something) instead of the post content.

It'd also only work for new or updated likes (and bookmarks, and so on), because that's when the title gets saved/overwritten.

It looks at what's in the "Like" block before trying to fetch the page, so if the remote server is giving us a crappy title (or blocking WordPress from fetching the page), whatever you manually enter into the block takes precedence.

For note archives, I'd stick with post content (because only bookmarks and reposts will get the title of the page they link to, the other note types won't).

**Comment by janboddez** [comment]
I'm still figuring out how to tackle this. Would have to try out more themes ... see how things are displayed.

> For note archives, I'd stick with post content (because only bookmarks and reposts will get the title of the page they link to, the other note types won't).

The plugin will add `.p-name` to bookmark titles and `.screen-reader-text` to "regular" note titles, so it should be okay. But may require a line or so of custom CSS to get things to align nicely (depending on the theme).

**Comment by janboddez** [comment]
I'm going to call this covered by the (possibly confusing) "Have like and bookmark titles reflect ..." setting. (In combination, if needed, with the "Exempt like and bookmark titles from being auto-hidden" setting.)

----

One (recent) example that uses this setup: https://build.boddez.net/likes/.

You'll notice that the Post Date block links to the "single" like, but that the title as shown on the archive page links to the "liked," i.e., external, page. That's the idea.

We could've also chosen to instead show the Post Content (which, thanks to the "new" Like block, also shows the "liked" page's title, and a link to it).

Both are equally valid, although I do think it makes sense to have a "heading" in your HTML for entries like these, so if I'd chosen to show the full content, I would've probably _kept_ the title (and opted _hide_ it through CSS or the "auto-hide setting" only rather than altogether remove it).

**Comment by janboddez** [comment]
(That's not to say things can't be improved. See #92, #97 ...)
