### ISSUE TITLE
Have Facepile block support Webmention plugin

### ISSUE THREAD

**Issue by janboddez** [janboddez/indieblocks#75]
For the facepile block (and excluding likes, etc. from the list of "regular" comments).

This is not too hard to do "hardcoded," but maybe a filter would be better. Not sure if possible.

Plus we'd need to do this for the v4 version (uses custom fields for storing a webmention's type) of said plugin, and for the upcoming v5 (uses the `comment_type` column).

**Comment by janboddez** [comment]
v5 is out so maybe we can look into this again.

**Comment by janboddez** [comment]
Back in the day, I experimented with adding comments with a `semantic_linkbacks_type` meta equal to like, bookmark, etc. to the Facepile block.

As of v5 of the Webmention plugin, I do believe we should instead look for comments with a `comment_type` of like or bookmark. (IndieBlocks itself uses meta still, but they're named slightky differently. Either way, this could work, and I think it'd be nice if we could separate the extra bits into a class of their own that we only load when this feature is enabled.)

**Comment by janboddez** [comment]
Like, favorite, bookmark and repost.

Reads are (currently) treated as mentions ... We can look into those later.

We can use `indieblocks_facepile_comments`, just run a 2nd query and add the new items in. Everything is (somewhat) cached, so that's better than nothing. Probably beats writing more advanced queries (for now).

Should probably also add a sort to the "default" facepile query.

**Comment by janboddez** [comment]
Facepile block now supports "Webmention mentions." There's no option to separately disable this behavior, but that's probably okay for now.

And CPTs are registered with trackback support (needed for webmention receival).

**Comment by Guanchishan** [comment]
Can the Webmention plugin and IndieBlocks be kept on at the same time in the future? 
Then I tried the new version of main branch on this github repo, and it seems that after setting the facepile block, the facepile still can't be displayed effectively. Maybe it's because github is not a stable version for now?

**Comment by janboddez** [comment]
It should be stable, but I can have another look. Maybe IndieBlocks' webmention avatars need to be enabled after all (just a guess). Or, it could be you need to enable avatars in WordPress' own Discussion settings.

The reason one probably should disable IndieBlocks' Webmention functionality (if the Webmention plugin is active) is because both plugins add a Webmention endpoint and both plugins will attempt to send webmentions on publish.

So you're going to get duplicate outgoing mentions and potentially weird incoming mention behavior.

I can add some extra checks, though, to, e.g., not add the endpoint if Webmention is active.

**Comment by janboddez** [comment]
Another thing is that, even if the Facepile block shows likes and reposts and so on, these still need to be "removed" from the "regular" comments, which is done (for now, I need to make this smarter) through yet another (IndieBlocks) setting.

**Comment by janboddez** [comment]
You can still enable IndieBlocks (and the Facepile block), by the way. As long as the "Enable Webmention" setting if disabled, you should be okay.

**Comment by janboddez** [comment]
> The reason one probably should disable IndieBlocks' Webmention functionality (if the Webmention plugin is active) is because both plugins add a Webmention endpoint and both plugins will attempt to send webmentions on publish.

The first of these concerns is now covered, by [ee72441](https://github.com/janboddez/indieblocks/commit/ee7244184faf34e815bafc9b4469b26ab25c2d4e).

The second one, I'm having a harder time deciding what to do. One should really only enable a single Webmention implementation ... but leaving this up to site admins to decide seems "better."

**Comment by Guanchishan** [comment]
There is one more thing I forgot to mention earlier.

![image](https://github.com/janboddez/indieblocks/assets/30859354/5e7cd13e-0286-484f-b255-39f00374b867)

After upgrading to the github version, all these checkboxes will be automatically deselected after saving the settings. That is, in essence, I can't even select them. I wonder if this could be the reason why I can't display the facepile successfully?

![image](https://github.com/janboddez/indieblocks/assets/30859354/d42ed6c1-b97d-410e-9202-2f099734e06a)

(screenshot of the version I'm using right now on wordpress.org)

**Comment by Guanchishan** [comment]
> The second one, I'm having a harder time deciding what to do. One should really only enable a single Webmention implementation ... but leaving this up to site admins to decide seems "better."

![image](https://github.com/janboddez/indieblocks/assets/30859354/83ab3b2c-eb5f-43e5-98e6-414eb09325f2)

Thanks! So on the matter of not recommending two webmentions enabled for the same site, would it be better to hint on the grey text here?

**Comment by janboddez** [comment]
> I wonder if this could be the reason why I can't display the facepile successfully?

I just noticed it too. That's a bug (that I'll fix)! But it's not the reason.

Did you add the Facepile block to your comments template part?

E.g., the following setup ...

![image](https://github.com/janboddez/indieblocks/assets/8428432/5cd96216-494d-4465-bc05-63a7b14d4546)

... should result in something like: https://build.boddez.net/notes/6f1cf9db20/. This (test) site uses the Webmention plugin (latest version) in combination with, obviously, the Facepile block.

**Comment by janboddez** [comment]
> So on the matter of not recommending two webmentions enabled for the same site, would it be better to hint on the grey text here?

I'm not sure. The idea behind IndieBlocks was that you should not need any other plugins to get going. (And since I already had a much simpler [than the other plugin] Webmention implementation lying around, I simply integrated that.) I don't want to confuse users even more ...

On the other hand, most people interested in trying IndieBlocks at all will likely be somewhat familiar with the "IndieWeb" and may already have a bunch of IndieWeb plugins installed.

That's why I say, "Look, IndieBlocks has 'everything you need,' but if you're already using a Webmention plugin that works for you and you'd rather keep it that way, that's okay, too. Simply leave the Webmention bit disabled."

I do agree, however, that the "Facepile" setting should probably go. In an ideal world, the plugin would detect the presence of a Facepile block (for a certain post), and "just" update the "comment count" accordingly. (Don't yet know if that is possible at all.)

**Comment by janboddez** [comment]
What I've done now is the following: if Webmention is active, IndieBlock will not output a Webmention endpoint link in the site's `head`.

What I could also do is simply hide the Webmention settings tab (on the condition that nothing was changed with regard to the default settings). That might be even better. Then if people wanted to try IndieBlocks' webmentions, I could tell them, "Simply deactivate the Webmention plugin first."

It's kind of like having Jetpack for whatever reason (its custom post types, or the image CDN, it doesn't matter), but running a different sitemap plugin that you like better. You would then leave Jetpack's sitemap functionality disabled.

Another example would be SEO plugins: there are so may of them, but you should probably only use one, to avoid conflicts. (Although the Jetpack comparison is probably the better one: there too you can separately enable only those modules that you need.)

**Comment by Guanchishan** [comment]
> Did you add the Facepile block to your comments template part?

Thank you for telling me! I've tried as you said. But it looks no work.

![image](https://github.com/janboddez/indieblocks/assets/30859354/484ea16b-b412-4e2c-b647-b3e3a6e023e3)

After saving, webmentions are still in the comment area.

![image](https://github.com/janboddez/indieblocks/assets/30859354/ae594e8c-56e1-4e16-b515-9c91271b121e)

---


By the way, is the syndication block also placed after the template of post page, so that links of syndicated copies can be displayed?

![image](https://github.com/janboddez/indieblocks/assets/30859354/8289f06d-7f61-48d2-ba5c-c45970d756f2)

I tried to put a syndication block. It tells me "This block encountered an error and could not be previewed." And after saving, there are no syndicated links displayed.

**Comment by janboddez** [comment]
> Thank you for telling me! I've tried as you said.

Hmm, all I can say is it looks OK in the first screenshot (the editor).

> After saving, webmentions are still in the comment area.

Oh ... they _should_ be "removed," but only when the "Facepile" setting is enabled (under the Webmention tab), and in your previous screenshot it was. (And they obviously also _should_ pop up as part of the Facepile block ...)

Re: the Syndication block, I thought I fixed a (similar) bug with the Syndication block. Can you look in your browser's DevTools and see if you can find a JavaScript error? Could also be you need to force-reload the JS (the cache busting mechanism likely doesn't work for the GitHub version). If the issue is that `meta is undefined`, that should be fixed (in the latest `main`).

By default, the Syndication block only shows links by Share on Mastodon and Share on Pixelfed. But there is a filter through which additional links can be added, see also https://indieblocks.xyz/documentation/the-syndication-block/. I plan to still add documentation for the Syndication Links plugin specifically; it _is_ possible to add all "Syndication Links" using a filter callback.

**Comment by janboddez** [comment]
(Unrelated to the other items being discussed here, there seems to be https://github.com/pfefferle/wordpress-webmention/blob/6e4ed42bea05966ba85e4b05399348ea382ea951/includes/functions.php#L75, which we might want to call in order to disable it, since we're already separating [certain] mentions.)

**Comment by Guanchishan** [comment]
> Oh ... they should be "removed," but only when the "Facepile" setting is enabled (under the Webmention tab), and in your previous screenshot it was. (And they obviously also should pop up as part of the Facepile block ...)

"Facepile" setting is enabled. ![image](https://github.com/janboddez/indieblocks/assets/30859354/ac5fc55a-51b1-4920-ad04-fec648e5a6f2)

I tried to save the setting again, and it still no work. No facepile displayed, and webmentions are in the comments area.

**Comment by janboddez** [comment]
The plugin uses this bit of code does the mention filtering (taking them out of the comments list).

Are you perhaps also using one of these hooks? (Or maybe another plugin does? Disabling them one by one might help find the culprit.)
```
$options = get_options();
if ( ! empty( $options['webmention_facepile'] ) ) {
	add_action( 'pre_get_comments', array( Webmention::class, 'comment_query' ) );
	add_filter( 'get_comments_number', array( Webmention::class, 'comment_count' ), 999, 2 );
}
```

This here bit of code gets the "facepile" mentions (the above hook is removed before we do so, in order to be able to fetch them at all):
```
// The Webmention plugin's mentions use "proper" comment types.
$args = array(
	'post_id'  => $post_id,
	'fields'   => 'ids',
	'status'   => 'approve',
	'type__in' => apply_filters( 'indieblocks_facepile_kinds', array( 'bookmark', 'like', 'repost' ), $post_id ),
);
if ( 0 !== get_current_user_id() ) {
	$args['include_unapproved'] = array( get_current_user_id() );
}
$webmention_comments = new \WP_Comment_Query( $args );
```
Of course in this second snippet, any other `pre_get_comments` action would _also_ affect what gets returned.

The Webmention plugin, I believe, must do some similar filtering, but I haven't seen a conflict on my test sites. (v5.1.0 introduced a different conflict, but that can be fixed by disabling the Webmention plugin's own "separate mentions" setting---after all, we are already using a block-based solution to accomplish the same thing.)

**Comment by janboddez** [comment]
@Guanchishan Long story short: if anything else is using `pre_get_comments`, that may be causing the issue.

Also, if you have access to the database, might be good to check these mentions' (in the `<prefix>_comments` table) `comment_type`. If they were created by the Webmention plugin and the upgrade to v5 went OK, the type should be `like`, `bookmark`, and so on.

If their type is empty or `comment`, then perhaps something went wrong with the upgrade; either way, IndieBlocks would then not pick them up.

**Comment by Guanchishan** [comment]
Hello 👋🏻 I succeeded. 
I don't know what happened - but it did happen - when I manually installed IndieBlocks 0.7.1 on GitHub, 0.7.0 was not automatically deleted, but left in WordPress. Later, I downloaded 0.8.0 from GitHub, and the upgrade behaviour also automatically deleted the version 0.7.1, and the unexpected remaining version 0.7.0 was not affected at all. The extra IndieBlocks plug-in cannot be found in the WordPress dashboard at all. I have disabled almost all plug-ins, and the bug of this issue has not been solved. 
Later, I found two IndieBlocks in the plug-in management interface of the Jetpack mobile application. 
After I deleted the extra IndieBlocks, the words "Likes, Bookmarks, and Reposts" were displayed, but no facepile appeared. But I know it's because I don't use IndieBlocks as a webmention client. I enabled the Webmention plug-in and enabled the option of avatar. 
Then everything was solved. It works well in my WordPress site.
Thank you again for your patient guidance!

**Comment by janboddez** [comment]
Cool! Just to be clear, only adding the Facepile block (and enabling avatars in WP's discussion settings) should be enough to show the facepile.

To avoid duplicates, however, one should also enable the following setting (everything else can be left disabled):
![image](https://github.com/janboddez/indieblocks/assets/8428432/d9d323cd-a411-422b-bf52-2a5b4c4c4729)

Or at least, that's how it works for me.

**Comment by janboddez** [comment]
Alternatively, the Webmention plugin's own setting to separate (certain) mentions into a facepile seems to now also work on my install. That is, there is a bug in Webmention v5.1.0, but once that fixed it also seems to work OK.

(That said, I of course like the block-based solution better.) :-D

**Comment by Guanchishan** [comment]
Thank you for your reply, you have added an important piece of information!

My situation here is with enabled avatars in WP's discussion settings, if I don't open this option in Webmentions:

![image](https://github.com/janboddez/indieblocks/assets/30859354/3faee4b4-62fb-4154-a55b-c2e9d530130b)

There will be no webmentions' facepile here:

![image](https://github.com/janboddez/indieblocks/assets/30859354/31fca98a-c157-4661-851a-7e3c20c379bc)

When I open, it displays:

![image](https://github.com/janboddez/indieblocks/assets/30859354/a88f8386-6d28-4e11-a791-a931d4f13098)

Of course, I know it's because I don't have IndieBlocks as my webmention client.
Then I also found out that indeed, as you said, IndieBlock's avatar option doesn't need to be enabled at this point either.

![image](https://github.com/janboddez/indieblocks/assets/30859354/84becbab-4c5b-4dd4-8907-9df2997e74ac)
(IndieBlocks setting page)

In fact, what attracts me to continue using the WP Webmention plugin is that it will provide an input box to fill in the webmention link:

![image](https://github.com/janboddez/indieblocks/assets/30859354/39913931-74c1-4a48-8def-736e7a0d0d8c)

Otherwise I would have been able to use the IndieBlocks plugin completely :-D

Thank you again for developing it!

**Comment by janboddez** [comment]
> ... if I don't open this option in Webmentions, [t]here will be no webmentions' facepile

Ah, that's good to know! I think I missed that one.

What happens is, it does find the mentions, but nothing is displayed because it can't find the avatars. I'll look into "fixing" this by falling back to the default avatar (which is what I do in IndieBlocks' avatar code, which in this case isn't called).

> [W]hat attracts me to continue using the WP Webmention plugin is that it will provide an input box to fill in the webmention link

This is a good point, someone else has already suggested to "copy" this feature, too. I'm still undecided.
