### ISSUE TITLE
Query block that shows posts, notes, likes, reblogs, comments

### ISSUE THREAD

**Issue by alizehctl** [janboddez/indieblocks#86]
I'm trying to figure out a way in which I can create a [tumblr-like microblog feed](https://piperhaywood.com) on the homepage of my site. Whether it's a long-form post, note, like, reblog, reply, they'd all show up in the query.

Is there any way to achieve this currently with this plugin? I'm using the default Twenty Twenty-Three theme.

**Comment by janboddez** [comment]
**Update: There is in a fact an actual plugin setting for _what the snippet below tries to accomplish_.**

~~Yes, through a `pre_get_posts` filter (which is how the plugin adds notes to WordPress' main RSS feed, if that option is enabled).~~

(It'd be great if you could just modify the home template's Query Loop attributes, but it currently only allows for one post type rather than multiple.)

~~Example PHP snippet:~~
```
<?php

add_filter( 'pre_get_posts', function( $query ) {
  if ( is_admin() ) {
    // Affect only the front end.
    return $query;
  }

  if ( ! $query->is_main_query() ) {
    // Affect only the page's main query.
    return $query;
  }

  if ( ! empty( $query->query_vars['suppress_filters'] ) ) {
    // Respect the `suppress_filters` argument.
    return $query;
  }

  if ( ! $query->is_home() ) {
    // Affect only the main blog page (either the homepage or a static blog page).
    return $query;
  }

  $post_types = $query->get( 'post_type' ); // The "default" post type.
  $post_types = ! empty( $post_types ) ? $post_types : array( 'post' ); // If no default was set, start with the "post" type.

  if ( is_string( $post_types ) ) {
    // If `post_type` was defined in string format, convert it to an array.
    $post_types = explode( ',', $post_types );
  }

  // Now, add our post types.
  $post_types   = array_filter( (array) $post_types );
  $post_types[] = 'indieblocks_note';
  $post_types[] = 'indieblocks_like';

  // Get rid of duplicates, if any.
  $query->set( 'post_type', array_unique( $post_types ) );

  // Phew!
  return $query;
}, 99 );
```
~~You could dump that in a "mu-plugin" and it _should_ just work. (I did test it really quickly.)~~

You wouldn't even have to use the like post type; you could view likes as "just a note" with a Like block/"like markup" in it. (I originally chose Custom Post Types in order to have notes, likes, and regular posts all separated _on the back end_, knowing that I could always use hooks to "recombine" them where needed.)

A different approach (but then you'd miss out on IndieBlocks' other features, obviously), is to instead use WordPress' built-in Post Formats and only use the default "post" type. Or another kind of custom taxonomy. Also, as all posts would be of a single post type, there would be no back-end separation at all. (But that may be more of an advantage, in your case. Well, I couldn't tell.)

Come to think of it, you could also skip the CPTs altogether and just use IndieBlocks' blocks to markup "regular" posts. But then it couldn't tell a note from an "article" and thus wouldn't know when (not) to hide a (note's) title.

**Comment by janboddez** [comment]
I just realized your example site uses all posts and Post Formats. So you could also just do that, forget about the Post Types and the code above, and _still_ use the (reply, bookmark, etc.) blocks (and the microformats option, for instance) whenever you see fit.

There isn't really "one correct way" to use this plugin (which may cause some people to find it confusing) ... :-D

Your theme will probably not auto-hide titles for, e.g., the aside or status Post Format, but a bit of custom CSS goes a long way. (IndieBlocks "solves" this by adding the `screen-reader-text` class for, well, most note and like titles.) They would likely still show in your RSS (causing certain readers to interpret them as articles instead of notes). Not sure if that would be s a dealbreaker. (IndieBlocks' Custom Post Types, again, do some "magic" here, depending on how it's configured.)

**Comment by janboddez** [comment]
Oh, wait a minute. I wouldn't know about the WP.org version (which I'll be updating soon-ish), but the latest GitHub version ("main" branch) definitely already supports this. So you would no longer need the snippet above! :-D

![image](https://github.com/janboddez/indieblocks/assets/8428432/e676ebc5-ceb2-454b-9458-ca55bc14d7fc)

**Comment by janboddez** [comment]
Next version will also have "Include in author archive" settings so that one could use WordPress' default author archives to set up a (per-user) "stream" that contains all long-form (i.e., regular) and short-form (notes, links, or both) post types. (And then the homepage can remain untouched. Or not.)

**Comment by janboddez** [comment]
My own author archive (https://jan.boddez.net/author/jan) currently lists both posts ("articles") and notes (including bookmarks, replies, and so on).

![image](https://github.com/janboddez/indieblocks/assets/8428432/56c18c97-22ee-4a0d-a713-f51a5ae25212)
